import math
import time

onoff=input("")



print ("Welcome to the Multi puropse device Version 3.0")



print ("Choose the desired speed of the Device")
print ("1-Beginner Speed")
print ("2-Intermediate Speed")
print ("3-Everyday user Speed")
po=int(input(""))
if po==1:
	div=1
	divi=1
elif po==2:
	div=2
	divi=100000
elif po==3:
	div=100000
	divi=100000
else:
	print ("Invalid Speed")
	time.sleep(1)
	print ("Continuing with Beginner Speed")
	div=1


while onoff=="on":
	time.sleep(2)
	print ("_")
	print (" ")
	print (" ") 
	print ("Which calculator Do you want")
	time.sleep(0.5/div)
	print ("Use tc for trigonometric calculator")
	time.sleep(0.5/div)
	print ("Use sc for student calculator")
	time.sleep(0.5/div)
	print ("Use bc for banking calculator")
	time.sleep(0.5/div)
	print ("Use scc for scientific calculator")
	time.sleep(0.5/div)
	print ("Use cc for currency converter")
	time.sleep(2/divi)
	calc=input("")
	if calc=="sc":
		print ("Enter a number")
		a=float(input(""))
		time.sleep(1/divi)
		print ("Valid Operators are :")
		time.sleep(1/div)
		print ("+ for addition")
		time.sleep(0.5/div)
		print ("- for subtraction")
		time.sleep(0.5/div)
		print ("* for multiplication")
		time.sleep(0.5/div)
		print ("/ for division")
		time.sleep(0.5/div)
		print ("% for percentage")
		time.sleep(0.5/div)
		print ("< for less than")
		time.sleep(0.5/div)
		print ("> for greater than")
		time.sleep(0.5/div)
		print ("** for power")
		time.sleep(0.5/div)
		print ("inv for inverse")
		time.sleep(1/div)
		print ("Enter an operator")
		x=input("")
		b=float(input("Enter a number, (For inverse, enter 1) "))
		print ("Calculating")
		time.sleep(0.15)
		print ("Calculating.")
		time.sleep(0.15)
		print ("Calculating..")
		time.sleep(0.15)
		print ("Calculating...")
		time.sleep(0.15)
		print ("Calculating....")
		time.sleep(0.15)
		print ("Calculating.....")
		time.sleep(0.15)
		if (x=="+"):
			k=a+b
			print("answer is",k)
		elif (x=="-"):
			l=a-b
			print("answer is",l)
		elif (x=="*"):
			m=a*b
			print("answer is",m)
		elif (x=="/"):
			n=a/b
			print("answer is",n)
		elif (x=="%"):
			j=a/100
			o=j*b
			print("answer is",o)
		elif (x=="<"):
			if (a<b):
				print("It is true")
			else:
				print("It is false")
		elif (x==">"):
			if (a>b):
				print("It is true")
			else:
				print("It is false")
		elif (x=="**"):
			p=a**b
			print("answer is",p)
		elif (x=="inv"):
			print ("answer is",1/a)
		else:
			print ("Cheking for validity of Operator")
			time.sleep(2)
			print("invalid operator")
	elif calc=="tc":
		print ("Valid operators are :")
		time.sleep(0.5/div)
		print ("sin")
		time.sleep(0.5/div)
		print ("cos")
		time.sleep(0.5/div)
		print ("tan")
		time.sleep(0.5/div)
		print ("cosec")
		time.sleep(0.5/div)
		print ("sec")
		time.sleep(0.5/div)
		print ("cot")
		time.sleep(0.5/div)
		print ("convert [Converts the angle from degree to radian]")
		time.sleep(1/div)
		functc=input("Enter the operator ")
		time.sleep(0.5/div)
		angle1=float(input("Enter the angle in degrees "))
		angle=math.radians(angle1)
		a=math.sin(angle)
		b=round(a,2)
		c=math.cos(angle)
		d=round(c,2)
		e=math.tan(angle)
		f=round(e,2)
		print ("Calculating")
		time.sleep(0.15)
		print ("Calculating.")
		time.sleep(0.15)
		print ("Calculating..")
		time.sleep(0.15)
		print ("Calculating...")
		time.sleep(0.15)
		print ("Calculating....")
		time.sleep(0.15)
		print ("Calculating.....")
		time.sleep(0.15)
		if functc=="sin":
			print (b)
		if functc=="cos":
			print (d)
		if functc=="tan":
			print (f)
		if functc=="cosec":
			print (1/b)
		if functc=="sec":
			print (1/d)
		if functc=="cot":
			print (1/f)
		if functc=="convert":
			print (angle)
	elif calc=="scc":
		print ("Valid operator are :")
		time.sleep(0.5/div)
		print ("ln for natural log")
		time.sleep(0.5/div)
		print ("log for log to the base 10")
		time.sleep(0.5/div)
		funscc=input("Enter the operator ")
		time.sleep(1/div)
		number=float(input("Enter the number "))
		print ("Calculating")
		time.sleep(0.15)
		print ("Calculating.")
		time.sleep(0.15)
		print ("Calculating..")
		time.sleep(0.15)
		print ("Calculating...")
		time.sleep(0.15)
		print ("Calculating....")
		time.sleep(0.15)
		print ("Calculating.....")
		time.sleep(0.15)
		if funscc=="ln":
			print (math.log(number))
		if funscc=="log":
			print (math.log10(number))
	elif calc=="bc":
		print ("Valid functions are :")
		time.sleep(0.5/div)
		print ("SI for simple interest")
		time.sleep(0.5/div)
		print ("CI for compound interest")
		time.sleep(0.5/div)
		funbc=input("Enter SI for simple interest and CI for compound interest ")
		if funbc=="SI":
			p=int(input("Enter Amount deposited "))
			time.sleep(0.5/div)
			r=float(input("Rate of Interest per annum "))
			time.sleep(0.5/div)
			t=int(input("Enter time period in years(Timne period should be greater than 1)"))
			i=p*r*t/100
			print ("Calculating")
			time.sleep(0.15)
			print ("Calculating.")
			time.sleep(0.15)
			print ("Calculating..")
			time.sleep(0.15)
			print ("Calculating...")
			time.sleep(0.15)
			print ("Calculating....")
			time.sleep(0.15)
			print ("Calculating.....")
			time.sleep(0.15)
			print ("Simple Interest is")
			print (i)
			time.sleep(0.5)
			print ("Amount received after simple interest is ")
			print (i+p)
		if funbc=="CI":
			p=int(input("Enter Amount deposited "))
			time.sleep(0.5/div)
			r=float(input("Rate of Interest per annum"))
			time.sleep(0.5/div)
			n=int(input("Number of times compounded per annum"))
			time.sleep(0.5/div)
			t=int(input("Enter time period in years(Time period should be greater than 1)"))
			print ("Calculating")
			time.sleep(0.15)
			print ("Calculating.")
			time.sleep(0.15)
			print ("Calculating..")
			time.sleep(0.15)
			print ("Calculating...")
			time.sleep(0.15)
			print ("Calculating....")
			time.sleep(0.15)
			print ("Calculating.....")
			time.sleep(0.15)			
			x=r/n
			j=x/100
			y=1+j
			z=n*t
			k=y**z
			a=p*k
			c=a-p
			round1=round(c,2)
			round2=round(a,2)
			print ("Compound Interest is ")
			print (round1)
			time.sleep(1)
			print ("Amount after compounding is ")
			print (round2)
	elif calc=="cc":
		print ("Disclaimer: This conversion is valid according to the year 2021 and are subject to change as time passes")
		time.sleep(0.5/div)
		print ("valid currency conversions are:")
		time.sleep(0.5/div)
		print ("Enter 1 for INR to USD")
		time.sleep(0.5/div)
		print ("Enter 2 for INR to Australian Dollar")
		time.sleep(0.5/div)
		print ("Enter 3 for INR to EURO")
		time.sleep(0.5/div)
		print ("Enter 4 for INR to Pound")
		time.sleep(0.5/div)
		print ("Enter 5 for INR to YEN")
		time.sleep(0.5/div)
		print ("Enter 1* for USD to INR")
		time.sleep(0.5/div)
		print ("Enter 2* for Australian Dollar to INR")
		time.sleep(0.5/div)
		print ("Enter 3* for EURO to INR")
		time.sleep(0.5/div)
		print ("Enter 4* for Pound to INR")
		time.sleep(0.5/div)
		print ("Enter 5* for YEN to INR")
		time.sleep(0.5/div)
		curr=input("")
		if curr=="1":
			INR=float(input("Enter the Amount in INR "))
			print ("Calculating")
			time.sleep(0.15)
			print ("Calculating.")
			time.sleep(0.15)
			print ("Calculating..")
			time.sleep(0.15)
			print ("Calculating...")
			time.sleep(0.15)
			print ("Calculating....")
			time.sleep(0.15)
			print ("Calculating.....")
			time.sleep(0.15)			
			USD=INR*0.013
			print ("Your Amount in USD is",USD)	
		if curr=="2":
			INR=float(input("Enter the Amount in INR "))
			print ("Calculating")
			time.sleep(0.15)
			print ("Calculating.")
			time.sleep(0.15)
			print ("Calculating..")
			time.sleep(0.15)
			print ("Calculating...")
			time.sleep(0.15)
			print ("Calculating....")
			time.sleep(0.15)
			print ("Calculating.....")
			time.sleep(0.15)			
			AD=INR*0.018
			print ("Your Amount in Australian Dollar is",AD)
		if curr=="3":
			INR=float(input("Enter the Amount in INR "))
			print ("Calculating")
			time.sleep(0.15)
			print ("Calculating.")
			time.sleep(0.15)
			print ("Calculating..")
			time.sleep(0.15)
			print ("Calculating...")
			time.sleep(0.15)
			print ("Calculating....")
			time.sleep(0.15)
			print ("Calculating.....")
			time.sleep(0.15)			
			EURO=INR*0.011
			print ("Your Amount in EURO is",EURO)
		if curr=="4":
			INR=float(input("Enter the Amount in INR "))
			print ("Calculating")
			time.sleep(0.15)
			print ("Calculating.")
			time.sleep(0.15)
			print ("Calculating..")
			time.sleep(0.15)
			print ("Calculating...")
			time.sleep(0.15)
			print ("Calculating....")
			time.sleep(0.15)
			print ("Calculating.....")
			time.sleep(0.15)			
			P=INR*0.0097
			print ("Your Amount in Pound is",P)
		if curr=="5":
			INR=float(input("Enter the Amount in INR "))
			print ("Calculating")
			time.sleep(0.15)
			print ("Calculating.")
			time.sleep(0.15)
			print ("Calculating..")
			time.sleep(0.15)
			print ("Calculating...")
			time.sleep(0.15)
			print ("Calculating....")
			time.sleep(0.15)
			print ("Calculating.....")
			time.sleep(0.15)			
			YEN=INR*1.52
			print ("Your Amount in YEN is",YEN)
		if curr=="1*":
			usd=float(input("Enter the Amount in USD "))
			print ("Calculating")
			time.sleep(0.15)
			print ("Calculating.")
			time.sleep(0.15)
			print ("Calculating..")
			time.sleep(0.15)
			print ("Calculating...")
			time.sleep(0.15)
			print ("Calculating....")
			time.sleep(0.15)
			print ("Calculating.....")
			time.sleep(0.15)			
			INR=usd*74.94
			print ("Your Amount in INR is",INR)
		if curr=="2*":
			ad=float(input("Enter the Amount in Australian Dollar "))
			print ("Calculating")
			time.sleep(0.15)
			print ("Calculating.")
			time.sleep(0.15)
			print ("Calculating..")
			time.sleep(0.15)
			print ("Calculating...")
			time.sleep(0.15)
			print ("Calculating....")
			time.sleep(0.15)
			print ("Calculating.....")
			time.sleep(0.15)			
			INR=ad*56
			print ("Your Amount in INR is",INR)
		if curr=="3*":
			euro=float(input("Enter the Amount in Euro "))
			print ("Calculating")
			time.sleep(0.15)
			print ("Calculating.")
			time.sleep(0.15)
			print ("Calculating..")
			time.sleep(0.15)
			print ("Calculating...")
			time.sleep(0.15)
			print ("Calculating....")
			time.sleep(0.15)
			print ("Calculating.....")
			time.sleep(0.15)			
			INR=euro*87.32
			print ("Your Amount in INR is",INR)
		if curr=="4*":
			p=float(input("Enter the Amount in Pound "))
			print ("Calculating")
			time.sleep(0.15)
			print ("Calculating.")
			time.sleep(0.15)
			print ("Calculating..")
			time.sleep(0.15)
			print ("Calculating...")
			time.sleep(0.15)
			print ("Calculating....")
			time.sleep(0.15)
			print ("Calculating.....")
			time.sleep(0.15)			
			INR=p*103.27
			print ("Your Amount in INR is",INR)
		if curr=="5*":
			yen=float(input("Enter the Amount in Yen "))
			print ("Calculating")
			time.sleep(0.15)
			print ("Calculating.")
			time.sleep(0.15)
			print ("Calculating..")
			time.sleep(0.15)
			print ("Calculating...")
			time.sleep(0.15)
			print ("Calculating....")
			time.sleep(0.15)
			print ("Calculating.....")
			time.sleep(0.15)			
			INR=yen*0.66
			print ("Your Amount in INR is",INR)
	else:
		print ("Checking for validity of calculator")
		time.sleep(2)
		print ("Invalid calculator")
